
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Entry inputEntry;

	private global::Gtk.Button applyButton;

	private global::Gtk.Entry resultEntry;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = "HelloWorld";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.inputEntry = new global::Gtk.Entry();
		this.inputEntry.CanFocus = true;
		this.inputEntry.Name = "inputEntry";
		this.inputEntry.IsEditable = true;
		this.inputEntry.MaxLength = 50;
		this.inputEntry.InvisibleChar = '●';
		this.vbox1.Add(this.inputEntry);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.inputEntry]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.applyButton = new global::Gtk.Button();
		this.applyButton.CanFocus = true;
		this.applyButton.Name = "applyButton";
		this.applyButton.UseUnderline = true;
		this.applyButton.Label = "Apply";
		this.vbox1.Add(this.applyButton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.applyButton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.resultEntry = new global::Gtk.Entry();
		this.resultEntry.CanFocus = true;
		this.resultEntry.Name = "resultEntry";
		this.resultEntry.IsEditable = false;
		this.resultEntry.InvisibleChar = '●';
		this.vbox1.Add(this.resultEntry);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.resultEntry]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 470;
		this.DefaultHeight = 298;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.applyButton.Clicked += new global::System.EventHandler(this.OnApplyButtonClicked);
	}
}
